### ISSUE TITLE
Macへのbitsインストール

### ISSUE THREAD

**Issue by YoshitakaNagai** [RenFukatsu/.joho-ta-tools#3]
https://qiita.com/granddaifuku/items/c26b58b89d73b4a3de98

**Comment by YoshitakaNagai** [comment]
https://qiita.com/EngTks/items/ffa2a7b4d264e7a052c6

**Comment by YoshitakaNagai** [comment]
$ brew install gcc
$ ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
$ cd ~/
$ mkdir vsc_run
$ cd vac_run/
$ vim cpp.sh
### cpp.sh
```
#!/bin/sh
file = $1
objfile = `echo $f | sed 's/\.[^\.]*$//'`

g++ -g -o $objfile $file
./$objfile
```

$ cd /usr/local/
$ find . -name "stdc++.h"
(./Cellar/gcc/9.3.0_1/include/c++/9.3.0/x86_64-apple-darwin19/bits/stdc++.h)
$ mkdir /usr/local/include/bits
$ cp ./Cellar/gcc/9.3.0_1/include/c++/9.3.0/x86_64-apple-darwin19/bits/stdc++.h /usr/local/include/bits/

**Comment by RenFukatsu** [comment]
bits/stdc++.hの導入ではなく、clangでも通るようにしてみたのですがどうでしょうか。
手元のubuntuでのclang++でのテストは大丈夫でした。
